---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: penale-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penale-services
  template:
    metadata:
      labels:
        app: penale-services
    spec:
      containers:
      - name: penale-services
        image: 090380/penale-sapp-v1:1.01
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: penale-services
  labels:
    app: penale-services
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    nodePort: 31200
  selector:
    app: penale-services