spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://gateway-services:8888
    discovery:
      enabled: true
    gateway:
      #            default-filters:
      #                - TokenRelay

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            add-to-simple-url-handler-mapping: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.100.218:8080/auth/realms/penale-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: penale-app
            client-secret: G92uLXt3EYbxZL0Kf57wHLQ2mlJnPLOp

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-services:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888

logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
